"use strict";
let audioContext=null,musicTimer=null,nextNoteTime=0,melodyIndex=0;
function ensureAudio(){if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume()}
function playTone(frequency,start,duration,type="square",volume=.025,force=false){if(!audioContext||(!state.musicOn&&!force))return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.setValueAtTime(frequency,start);g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.012);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(g).connect(audioContext.destination);o.start(start);o.stop(start+duration+.02)}
function scheduleMusic(){if(!audioContext||!state.musicOn)return;const melody=[440,523.25,587.33,659.25,587.33,523.25,440,392,440,523.25,659.25,783.99,659.25,587.33,523.25,440];while(nextNoteTime<audioContext.currentTime+.25){const note=melody[melodyIndex%melody.length];playTone(note,nextNoteTime,.16,"square",.018);if(melodyIndex%4===0)playTone(note/2,nextNoteTime,.28,"triangle",.012);nextNoteTime+=.22;melodyIndex++}}
function startMusic(){ensureAudio();if(!state.musicOn)return;clearInterval(musicTimer);nextNoteTime=audioContext.currentTime+.05;melodyIndex=0;scheduleMusic();musicTimer=setInterval(scheduleMusic,100)}
function stopMusic(){clearInterval(musicTimer);musicTimer=null}
function toggleMusic(){state.musicOn=!state.musicOn;$("musicButton").classList.toggle("muted",!state.musicOn);if(state.musicOn)startMusic();else stopMusic()}
function playSfx(kind){ensureAudio();const now=audioContext.currentTime;if(kind==="correct"){playTone(523.25,now,.09,"square",.04,true);playTone(659.25,now+.1,.1,"square",.04,true);playTone(783.99,now+.2,.18,"square",.045,true)}else if(kind==="wrong"){playTone(220,now,.13,"sawtooth",.025,true);playTone(174.61,now+.12,.2,"sawtooth",.025,true)}else playTone(kind==="drop"?392:659.25,now,kind==="drop"?.07:.035,"square",.018,true)}
function speakOrder(){if(!("speechSynthesis" in window)||!state.order.length)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(`I would like ${formatFoodList(state.order)}.`);u.lang="en-US";u.rate=.82;u.pitch=1.05;window.speechSynthesis.speak(u)}
