"use strict";
const startScreen=$("startScreen"),gameScreen=$("gameScreen"),resultScreen=$("resultScreen"),foodGrid=$("foodGrid"),plate=$("plate"),plateItems=$("plateItems"),plateHint=$("plateHint"),toast=$("toast");
let toastTimer=null;
function showScreen(screen){[startScreen,gameScreen,resultScreen].forEach(x=>x.classList.add("hidden"));screen.classList.remove("hidden");window.scrollTo({top:0,behavior:"auto"})}
function showToast(message,type=""){clearTimeout(toastTimer);toast.textContent=message;toast.className=`toast show ${type}`;toastTimer=setTimeout(()=>toast.className="toast",2100)}
function updateHud(){$("coinCount").textContent=state.coins;$("questionNumber").textContent=Math.max(1,state.question);$("menuLevel").textContent=state.unlocked?"LEVEL 2":"LEVEL 1";$("unlockText").textContent=state.unlocked?"New dishes are now available!":`Earn ${Math.max(0,UNLOCK_COINS-state.coins)} more coins to unlock food!`}
function generateOrder(){const pool=availableFoods(),count=state.question>=3&&Math.random()<.48?2:1;state.order=shuffle(pool).slice(0,count).map(x=>x.id);$("orderSentence").textContent=`“I would like ${formatFoodList(state.order)}.”`}
function resetPlate(){state.plate=[];plateItems.innerHTML="";plateHint.classList.remove("hidden")}
function addFoodToPlate(foodId){if(state.plate.length>=2){showToast("The plate is full. Tap CLEAR to change it.","bad");return}if(state.plate.includes(foodId)){showToast("You already added this food.","bad");return}state.plate.push(foodId);const img=document.createElement("img");img.className="plate-food";img.alt=foodById(foodId).name;img.src=createFoodDataUrl(foodId);plateItems.appendChild(img);plateHint.classList.add("hidden");playSfx("drop")}
function attachDrag(card,canvas){let ghost=null,pointerId=null;const move=e=>{if(!ghost)return;ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`;const r=plate.getBoundingClientRect(),over=e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;plate.classList.toggle("drag-over",over)};const end=e=>{if(!ghost||e.pointerId!==pointerId)return;const r=plate.getBoundingClientRect(),over=e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;if(over)addFoodToPlate(card.dataset.foodId);plate.classList.remove("drag-over");ghost.remove();ghost=null;pointerId=null;try{card.releasePointerCapture(e.pointerId)}catch(_){}};card.addEventListener("pointerdown",e=>{if(state.finished)return;e.preventDefault();pointerId=e.pointerId;card.setPointerCapture(pointerId);ghost=document.createElement("div");ghost.className="drag-ghost";const img=document.createElement("img");img.alt="";img.src=canvas.toDataURL("image/png");ghost.appendChild(img);document.body.appendChild(ghost);move(e);playSfx("pick")});card.addEventListener("pointermove",move);card.addEventListener("pointerup",end);card.addEventListener("pointercancel",end)}
function renderFoodGrid(){foodGrid.innerHTML="";availableFoods().forEach(food=>{const card=document.createElement("button");card.type="button";card.className=`food-card${food.level===2?" new":""}`;card.dataset.foodId=food.id;card.setAttribute("aria-label",`Drag ${food.name} to the plate`);const canvas=document.createElement("canvas");canvas.width=64;canvas.height=64;drawFood(canvas,food.id);const label=document.createElement("span");label.textContent=food.name;card.append(canvas,label);attachDrag(card,canvas);foodGrid.appendChild(card)})}
function serveOrder(){if(state.finished||state.plate.length===0){showToast("Drag food to the plate first!","bad");return}const success=arraysMatch(state.plate,state.order);if(success){state.coins+=10;state.correct++;$("customer").className="customer happy";showToast("Correct! +10 coins","good");playSfx("correct")}else{state.coins=Math.max(0,state.coins-10);state.wrong++;$("customer").className="customer sad";showToast(`Wrong! The customer wanted ${formatFoodList(state.order)}. -10 coins`,"bad");playSfx("wrong")}state.history.push({question:state.question,request:formatFoodList(state.order),served:formatFoodList(state.plate),result:success?"Correct":"Wrong",coinsAfter:state.coins});if(!state.unlocked&&state.coins>=UNLOCK_COINS){state.unlocked=true;setTimeout(()=>showToast("LEVEL 2 UNLOCKED! New food added!","good"),900)}updateHud();setTimeout(nextQuestion,1350)}
function nextQuestion(){if(state.question>=TOTAL_QUESTIONS){finishGame();return}state.question++;$("customer").className="customer";resetPlate();renderFoodGrid();generateOrder();updateHud()}
function startGame(student){Object.assign(state,{student,coins:0,question:0,correct:0,wrong:0,unlocked:false,order:[],plate:[],history:[],finished:false,startedAt:new Date()});showScreen(gameScreen);renderFoodGrid();updateHud();startMusic();nextQuestion()}
function finishGame(){state.finished=true;stopMusic();const accuracy=Math.round(state.correct/TOTAL_QUESTIONS*100);$("finalCoins").textContent=state.coins;$("finalCorrect").textContent=`${state.correct}/${TOTAL_QUESTIONS}`;$("finalAccuracy").textContent=`${accuracy}%`;$("resultTitle").textContent=accuracy>=80?"Excellent service!":accuracy>=60?"Good job!":"Keep practising!";$("emailStatus").className="email-status";$("emailStatus").textContent="Sending the result to the teacher…";$("emailFallback").classList.add("hidden");showScreen(resultScreen);sendResultEmail()}
$("studentForm").addEventListener("submit",e=>{e.preventDefault();const student={name:clampText($("studentName").value,40),className:clampText($("studentClass").value,20),classNumber:clampText($("studentNumber").value,10)};if(student.name&&student.className&&student.classNumber)startGame(student)});
$("serveButton").addEventListener("click",serveOrder);$("clearButton").addEventListener("click",resetPlate);$("musicButton").addEventListener("click",toggleMusic);$("speakButton").addEventListener("click",speakOrder);$("downloadButton").addEventListener("click",downloadResult);$("playAgainButton").addEventListener("click",()=>{showScreen(startScreen);$("studentName").focus()});
document.addEventListener("visibilitychange",()=>{if(document.hidden)stopMusic();else if(!state.finished&&!gameScreen.classList.contains("hidden")&&state.musicOn)startMusic()});
